extends: 
  - airbnb-base
  - eslint-config-prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

env:
  node: true

rules:
#  indent: [error, tab]
#  no-tabs: off
  no-console: off
  no-unused-vars: 
    - error
    - { vars: all, args: after-used, ignoreRestSiblings: true, ignorePattern: '^_' }